//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8AccountStatusReview.Runner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\C8AccountStatusReview\\C8AccountStatusReview.MidYear\\Reports\\Cognitive" +
            "ReportsUnlocked.rdlc")]
        public string CognitiveReportsUnlockedPath {
            get {
                return ((string)(this["CognitiveReportsUnlockedPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\C8AccountStatusReview\\C8AccountStatusReview.MidYear\\Reports\\LeadingCo" +
            "horts.rdlc")]
        public string LeadingCohortsPath {
            get {
                return ((string)(this["LeadingCohortsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\C8AccountStatusReview\\C8AccountStatusReview.MidYear\\Reports\\SchoolMid" +
            "yearReport.rdlc")]
        public string MidYearReportPath {
            get {
                return ((string)(this["MidYearReportPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\C8AccountStatusReview\\C8AccountStatusReview.MidYear\\Reports\\Cognitive" +
            "Weaknesses.rdlc")]
        public string CognitiveWeaknessesPath {
            get {
                return ((string)(this["CognitiveWeaknessesPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\C8AccountStatusReview\\C8AccountStatusReview.MidYear\\Reports\\StatsChar" +
            "t.rdlc")]
        public string StatsChartPath {
            get {
                return ((string)(this["StatsChartPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\C8AccountStatusReview\\C8AccountStatusReview.MidYear\\Reports\\StudentsO" +
            "nTrack.rdlc")]
        public string StudentsOnTrackPath {
            get {
                return ((string)(this["StudentsOnTrackPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        public string C8Data {
            get {
                return ((string)(this["C8Data"]));
            }
        }
    }
}
